buildscript {
    repositories {
        mavenCentral()
        maven {
            name = "forge"
            url = "https://maven.minecraftforge.net/"
        }       
		maven {
            name = "github"
            url = "https://github.com/juanmuscaria/maven/raw/master"
        }
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle2:[2.3-1.0.0-SNAPSHOT,)'
    }
}

repositories {
	flatDir {
		dirs 'deps'
	}
}

apply plugin: 'eclipse'
apply plugin: 'maven-publish'
apply plugin: 'net.minecraftforge.gradle.forge'

version = mod_version
group = mod_group
archivesBaseName = mod_archives_name

[compileJava, compileTestJava]*.options*.encoding = 'UTF-8'
sourceCompatibility = targetCompatibility = compileJava.sourceCompatibility = compileJava.targetCompatibility = '1.8'

minecraft {
	version = "1.12.2-14.23.5.2847"
    mappings = "stable_39"
	runDir = "eclipse"
    
	replace '@VERSION@', project.version
	// makeObfSourceJar = false
}

processResources {

    from(sourceSets.main.resources.srcDirs) {
        include 'mcmod.info'
        expand 'version': project.version,
		'mod_id': mod_id,
		'mod_name': mod_name,
		'mod_author': mod_author,
		'mod_description': mod_description,
		'mc_version': mc_version,
		'mod_version': mod_version,
		'mod_icon': mod_icon
    }

    from(sourceSets.main.resources.srcDirs) {
        exclude 'mcmod.info'
    }
}

repositories {
    flatDir {
        dirs 'lib'
    }
    maven {
        name = "DVS1 Maven FS"
        url = "http://dvs1.progwml6.com/files/maven"
    }
    maven {
        url "https://cursemaven.com"
    }
    maven { url "https://jitpack.io" }
}


dependencies {
    //compile 'com.gitlab.lcoremodders:LucraftCore:22057cedd3'
    //compile 'curse.maven:lucraft-core-230651:2841048'
    //deobfCompile ('com.gitlab.lcoremodders:LucraftCore:5bec1f22')

    //compile 'curse.maven:pymtech-316946:2706385' 316946
    //compile 'curse.maven:lucraft-core-230651:3283571'
    //compile 'curse.maven:heroesexpansion-267462:2762537'
    //compile 'curse.maven:speedster-heroes-252318:2996769'
    //compile 'curse.maven:pymtech-316946:2706385'
    //compile 'curse.maven:endgame-addon-665792:3975622'
    //compile 'curse.maven:lantern-corps-universe-291355:3705877'

    deobfCompile "lucraft.core:LucraftCore:2.5.16-deobf"

    //deobfCompile files("lib/LucraftCore-1.12.2-2.2.4-deobf.jar")
}

task deobfJar(type: Jar) {
    from sourceSets.main.output
    classifier = 'deobf'
    manifest {
        attributes 'FMLCorePlugin': 'lucraft.mods.lucraftcore.core.LucraftCoreCoreMod', 'FMLCorePluginContainsFMLMod': 'true',
                'FMLAT': 'lucraftcore_at.cfg'
    }

}




task devJar(type: Jar) {
	classifier = 'dev'
	from sourceSets.main.output
}

task sourcesJar(type: Jar) {
	classifier = 'sources'
	from sourceSets.main.allSource
}

artifacts {
	archives devJar
	archives sourcesJar
    archives deobfJar
}



