# Gradle Specifications
org.gradle.jvmargs=-Xms256M -Xmx2G
org.gradle.daemon=false

# General Specifications
mc_version=1.12.2
mod_version=1.0.0-Template
forge_version=14.23.5.2855
mod_group=ua.archijk.templatelcmod
mod_id=templatelucraftmod
mod_name=Template LC Mod
mod_archives_name=TemplateLCMod
mod_author=ArchiJK
mod_icon=icon.png
mod_description= EN/UA/RU Discord - https://discord.gg/ZqsZc5Ad6m
mod_credits=Me, for making this amazing LC mod.
